console.log("This is Strings Tutorial.");
let a = "Himanshu";
console.log(a[0]);
console.log(a[1]);
console.log(a[2]);
console.log(a[3]);
console.log(a[4]);
// console.log(a[5]);
console.log(a.length);
let real_name = "Himanshu";
let friend = "Divya";
console.log("His Name is " + real_name + " and his Friends Name is " + friend);
console.log(`His Name is ${real_name} and his Friends Name is ${friend}`);
let b = "Valtryek";
console.log(b.toUpperCase());
console.log(b.toLowerCase());
console.log(b.length);
console.log(b.slice(1, 5));
console.log(b.slice(1));
console.log(b.replace("Val", "77"));
console.log(b.concat(a, "Prashant", "Laxmi", "Digesh"));
console.log(b);